// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	AccessToken string `json:"accessToken"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Order struct {
	ID        string  `json:"id"`
	SerialNo  string  `json:"serialNo"`
	Quantity  int     `json:"quantity"`
	Expense   float64 `json:"expense"`
	CreatedAt string  `json:"createdAt"`
	User      *User   `json:"user"`
}

type Query struct {
}

type User struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Email     string   `json:"email"`
	Phone     string   `json:"phone"`
	Address   *string  `json:"address,omitempty"`
	CreatedAt string   `json:"createdAt"`
	Orders    []*Order `json:"orders"`
}
