package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// Name is the resolver for the name field.
func (r *queryResolver) Name(ctx context.Context) (string, error) {
	return "lol name", nil
}

// Roll is the resolver for the roll field.
func (r *queryResolver) Roll(ctx context.Context) (string, error) {
	return "lol roll", nil
}

// Thikana is the resolver for the thikana field.
func (r *queryResolver) Thikana(ctx context.Context) (string, error) {
	return "lol thikana", nil
}
